version: "2.3"
services:
  ontop:
    container_name: ontop
    image: oegdataintegration/ontop:3.0.0
    env_file:
    volumes:
      - ../data:/data
      - ../results/ontop:/results
      - ../mappings:/mappings
      - ../queries:/queries  
  morph-csv:
    container_name: morph-csv
    image: oegdataintegration/morph-csv:1.0.0
    env_file:
    volumes:
      - ../data:/data
      - ../results/morph-csv:/results
      - ../mappings:/mappings
      - ../queries:/queries
      

  morph-xr2rml:
    container_name: morph-xr2rml
    image: oegdataintegration/morph-xr2rml:4.0.0
    volumes:
      - ../data:/data
      - ../results/morph-xr2rml:/results
      - ../mappings:/mappings
      - ../queries:/queries

  morph-rdb:
    container_name: morph-rdb
    image: oegdataintegration/morph-rdb:3.12.5
    volumes:
      - ../data:/data
      - ../results/morph-rdb:/results
      - ../mappings:/mappings
      - ../queries:/queries

  ontario:
    container_name: ontario
    image: oegdataintegration/ontario:0.3
    volumes:
      - ../data:/data
      - ./ontario/configurations:/configurations
      - ../results/ontario:/results
      - ../mappings:/mappings
      - ../queries:/queries