version: "1.0"
services:
 mysql:
   container_name: database
   image: mysql:5
   restart: always
   env_file: ./environment.properties
   expose: ["3306"]
 generator:
   container_name: diversi-obda-gen
   image: oegdataintegration/diversi-obda-gen:1.0
   restart: always
   env_file: ./environment.properties